repos:
  - repo: https://github.com/standard/standard
    rev: master
    hooks:
      - id: standard
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: master
    hooks:
      - id: stylelint
        additional_dependencies: ['stylelint@14.5.1', 'stylelint-config-standard@24.0.0']